import { Inter } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div
          style={{
            display: 'flex',
            justifyContent: 'spaceBetween',
            marginTop: '50px',
            textAlign: 'center',
          }}
        >
          <Link href={`/signup`} style={{ color: 'white', fontSize: '30px', marginLeft: '25px' }}>
            Register{' '}
          </Link>
          <Link href={`/signin`} style={{ color: 'white', fontSize: '30px', marginLeft: '25px' }}>
            Sign In{' '}
          </Link>
          <Link
            href={`/forgotpassword`}
            style={{ color: 'white', fontSize: '30px', marginLeft: '25px' }}
          >
            Forgot Password{' '}
          </Link>
          <Link
            href={`/checkemail`}
            style={{ color: 'white', fontSize: '30px', marginLeft: '25px' }}
          >
            Check Email{' '}
          </Link>
        </div>

        <div className={styles.center}>
          <Image
            alt={'Next.js Logo'}
            className={styles.logo}
            height={37}
            priority
            src={'/next.svg'}
            width={180}
          />
        </div>
      </main>
    </>
  )
}
